name: texno_bozor
description: A new sFlutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.1.0

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.8.4
  easy_localization: ^3.0.2
  shared_preferences: ^2.1.2
  zoom_tap_animation: ^1.1.0
  http: ^1.1.0
  provider: ^6.0.5
  firebase_core: ^2.15.0
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.1
  firebase_storage: ^11.2.5
  lottie: ^2.5.0
  image_picker: ^1.0.1
  carousel_slider: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/

